### ISSUE TITLE
[BUG] Group cache can create a memory leak

### ISSUE THREAD

**Issue by Hbeau** [OnapleRPG/CrowdBinding#15]
here is 2 `Hashset` that are never clear and can cause a memory leak

https://github.com/OnapleRPG/CrowdBinding/blob/master/src/main/java/com/onaple/crowdbinding/data/Group.java#L15

https://github.com/OnapleRPG/CrowdBinding/blob/master/src/main/java/com/onaple/crowdbinding/data/Invitation.java#L14

**Comment by obr-09** [comment]
Actually, I only see one in Group.java. Where would be the second one?

**Comment by obr-09** [comment]
The groups that are removed from the list are now cleaned from players.
