### ISSUE TITLE
Accepting an invitation when already in a group with multiple users should not be possible

### ISSUE THREAD

**Issue by obr-09** [OnapleRPG/CrowdBinding#3]
There should be a message that says something like "You are already in a group" when accepting an invitation.
Even better, inviting a player that is already in a group should tell you that the player is already in a group and auto cancel the invitation.
We could have both to ensure that the invitation is still available when the player accepts it.

**Comment by wytrem** [comment]
Accepting an invitation could also just make you leave the group you were in an join the one you're invited to.
